xsd2php:
  namespaces:
    'http://www.opentravel.org/OTA/2003/05': 'Devlabs91\TravelgateNotify\Models\Ota'
  destinations_php: 
    'Devlabs91\TravelgateNotify\Models\Ota': src/Models/Ota
  destinations_jms:
    'Devlabs91\TravelgateNotify\Models\Ota': src/Metadata/Ota
    